[sec_words]
  [sec_words.malicious]
    patterns = ['malicous']
  [sec_words.license]
    patterns = ['licence', 'lisence']
  [sec_words.counterfeit]
    patterns = ['counterfit', 'counter fit']
  [sec_words.program]
    patterns = ['progrm', 'progam']
  [sec_words.researchers]
    patterns = ['resaerchers']
  [sec_words.suspicious]
    patterns = ['supicious']
  [sec_words.prosecute]
    patterns = ['persecute', 'prosecutee']