[sec_words]
  [sec_words.malicious]
    patterns = ['malicous']
  [sec_words.license]
    patterns = ['licence', 'lisence']
  [sec_words.counterfeit]
    patterns = ['counterfit', 'counter fit']
  [sec_words.program]
    patterns = ['progrm', 'progam']
  [sec_words.researchers]
    patterns = ['researchers']
  [sec_words.fox]
    patterns = ['foxx', 'foxxx']
